-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / 
          (SELECT COUNT(1) 
           FROM USER_INFO
           WHERE YEAR(JOINED) = '2021'
          ), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
INNER JOIN USER_INFO UI
    ON OS.USER_ID = UI.USER_ID
    AND YEAR(JOINED) = '2021'
GROUP BY 1, 2;