-- 코드를 입력하세요
# SELECT FH.FLAVOR
# FROM FIRST_HALF FH
# INNER JOIN JULY J
#     ON FH.FLAVOR = J.FLAVOR
# GROUP BY J.FLAVOR
# ORDER BY FH.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC
# LIMIT 3;

WITH JULY_TEMP AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)
SELECT FH.FLAVOR
FROM FIRST_HALF FH
INNER JOIN JULY_TEMP JT
    ON FH.FLAVOR = JT.FLAVOR
ORDER BY FH.TOTAL_ORDER + JT.SUM_TOTAL_ORDER DESC
LIMIT 3;