-- 코드를 입력하세요
WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID,
        REVIEW_TEXT,
        REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(1) DESC LIMIT 1)
)
SELECT P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REVIEW_COUNT R
    ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY 3, 2