-- 코드를 입력하세요
WITH TOTAL_BOOK_SALES AS (
    SELECT B.BOOK_ID,
        B.CATEGORY,
        B.AUTHOR_ID,
        SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
    FROM BOOK B
    INNER JOIN BOOK_SALES BS
        ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE < '2022-02-01'
    GROUP BY B.AUTHOR_ID, B.CATEGORY
)
SELECT TBS.AUTHOR_ID,
    A.AUTHOR_NAME,
    TBS.CATEGORY,
    TBS.TOTAL_SALES
FROM TOTAL_BOOK_SALES TBS
INNER JOIN AUTHOR A
    ON TBS.AUTHOR_ID = A.AUTHOR_ID
ORDER BY 1, 3 DESC;