-- 코드를 입력하세요
# WITH TEMP AS (
#     SELECT HOST_ID
#     FROM PLACES
#     GROUP BY HOST_ID
#     HAVING COUNT(HOST_ID) >= 2
# )
# SELECT P.*
# FROM PLACES P
# INNER JOIN TEMP T ON P.HOST_ID = T.HOST_ID
# ORDER BY 1;

# SELECT *
# FROM PLACES
# WHERE HOST_ID IN (
#     SELECT HOST_ID
#     FROM PLACES
#     GROUP BY HOST_ID
#     HAVING COUNT(HOST_ID) >= 2
# )
# ORDER BY 1;

SELECT P.*
FROM PLACES P
INNER JOIN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2
) AS T ON P.HOST_ID = T.HOST_ID
ORDER BY P.ID