-- 코드를 입력하세요
SELECT CM.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CM
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    ON CM.CAR_ID = CH.CAR_ID
    AND CM.CAR_TYPE = '세단'
    AND START_DATE >= '2022-10-01' AND START_DATE < '2022-11-01'
GROUP BY 1
ORDER BY 1 DESC;